// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipybnukhfrllvjyhymye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlweWJudWtoZnJsbHZqeWh5bXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NjUxOTgsImV4cCI6MjA5MjM0MTE5OH0.VwGPS02CWGNgavOOude_oltJ6yhIrXJGCeWUAEDM6mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});